version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5005 
    ports:
      - "5005:5005"
    volumes:
      - ./wwwroot:/app/wwwroot
    network_mode: "host"

